# -*- coding: utf-8 -*-
"""RNN project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10uPFsf-RsRkP9R709yZnu50XHew9c3rb
"""

!pip install transformers

from transformers import pipeline, AutoModelForSequenceClassification, AutoTokenizer

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
pipe = pipeline('sentiment-analysis')

import random
import pandas as pd

def select_random_text(csv_file):
    # Read the CSV file into a pandas DataFrame
    df = pd.read_csv('/content/rnn_analysis.csv')

    # Select a random index
    random_index = random.randint(0, len(df) - 1)

    # Get the random text from the 'text' column
    random_text = df.loc[random_index, 'text']

    return random_text

# Example usage:
random_text = select_random_text('/content/rnn_analysis.')
print(random_text)
text1=random_text
out = pipe(text1)
result = out[0]  # Assuming you want the first result if multiple are returned
sentiment = result["label"]
score = round(result["score"], 2)
print(f"Sentiment: {sentiment}")
print(score)